var PRODUCTS = [
  {"id":"2001","sku":"venok-premium-s","brandCode":"venki","brand":"Авторская мастерская","series":"Венки","model":"Венок «Элегия» S","group":"venki","size":"S","btu":"-","area":0,"price":2500,"stock":"in_stock","stockLabel":"В наличии","descShort":"Авторская работа · Искусственные цветы","cardBenef":"Ручная работа · Стойкие материалы · Размер S","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер S"],"photo":"venok_2026-05-03_010950.png"},
  {"id":"2002","sku":"venok-premium-m","brandCode":"venki","brand":"Авторская мастерская","series":"Венки","model":"Венок «Элегия» M","group":"venki","size":"M","btu":"-","area":0,"price":3500,"stock":"in_stock","stockLabel":"В наличии","descShort":"Авторская работа · Искусственные цветы","cardBenef":"Ручная работа · Стойкие материалы · Размер M","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер M"],"photo":"venok_2026-05-03_013828.png"},
  {"id":"2003","sku":"venok-premium-l","brandCode":"venki","brand":"Авторская мастерская","series":"Венки","model":"Венок «Элегия» L","group":"venki","size":"L","btu":"-","area":0,"price":5000,"stock":"in_stock","stockLabel":"В наличии","descShort":"Авторская работа · Искусственные цветы","cardBenef":"Ручная работа · Стойкие материалы · Размер L","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер L"],"photo":"venok_2026-05-03_020034.png"},
  {"id":"2004","sku":"venok-lux-m","brandCode":"venki","brand":"Авторская мастерская","series":"Венки","model":"Венок «Тихий сад» M","group":"venki","size":"M","btu":"-","area":0,"price":4200,"stock":"in_stock","stockLabel":"В наличии","descShort":"Авторская работа · Искусственные цветы","cardBenef":"Ручная работа · Нежная палитра · Размер M","benefits":["Искусственные цветы","Авторская ручная работа","Нежная цветовая гамма","Размер M"],"photo":"venok_2026-05-02_001.png"},
  {"id":"2005","sku":"venok-lux-l","brandCode":"venki","brand":"Авторская мастерская","series":"Венки","model":"Венок «Тихий сад» L","group":"venki","size":"L","btu":"-","area":0,"price":6500,"stock":"in_stock","stockLabel":"В наличии","descShort":"Авторская работа · Искусственные цветы","cardBenef":"Ручная работа · Нежная палитра · Размер L","benefits":["Искусственные цветы","Авторская ручная работа","Нежная цветовая гамма","Размер L"],"photo":"venok_2026-05-03_111644.png"},
  {"id":"2006","sku":"korzinka-premium-s","brandCode":"korzinki","brand":"Авторская мастерская","series":"Корзинки","model":"Корзинка «Весенняя» S","group":"korzinki","size":"S","btu":"-","area":0,"price":1800,"stock":"in_stock","stockLabel":"В наличии","descShort":"Авторская работа · Искусственные цветы","cardBenef":"Ручная работа · Стойкие материалы · Размер S","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер S"],"photo":"korzinka_2026-05-01_001.png"},
  {"id":"2007","sku":"korzinka-premium-m","brandCode":"korzinki","brand":"Авторская мастерская","series":"Корзинки","model":"Корзинка «Весенняя» M","group":"korzinki","size":"M","btu":"-","area":0,"price":2800,"stock":"in_stock","stockLabel":"В наличии","descShort":"Авторская работа · Искусственные цветы","cardBenef":"Ручная работа · Стойкие материалы · Размер M","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер M"],"photo":"korzinka_2026-05-02_001.png"},
  {"id":"2008","sku":"korzinka-premium-l","brandCode":"korzinki","brand":"Авторская мастерская","series":"Корзинки","model":"Корзинка «Весенняя» L","group":"korzinki","size":"L","btu":"-","area":0,"price":4200,"stock":"in_stock","stockLabel":"В наличии","descShort":"Авторская работа · Искусственные цветы","cardBenef":"Ручная работа · Стойкие материалы · Размер L","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер L"],"photo":"ritual_2026-04-28_13-23-24_002.png"}
];

var PRODUCT_OVERRIDES = {};
