var PRODUCTS = [
  {"id":"2001","sku":"venok-premium-s","brandCode":"venki","brand":"Авторская мастерская","series":"Премиум венок","model":"Венок «Элегия» S","group":"venki","size":"S","btu":"-","area":0,"price":2500,"stock":"in_stock","stockLabel":"В наличии","descShort":"Венок · Размер S · Авторская работа","cardBenef":"Искусственные цветы · Ручная работа · Размер S","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер S"],"photo":"venok-premium-s.webp"},
  {"id":"2002","sku":"venok-premium-m","brandCode":"venki","brand":"Авторская мастерская","series":"Премиум венок","model":"Венок «Элегия» M","group":"venki","size":"M","btu":"-","area":0,"price":3500,"stock":"in_stock","stockLabel":"В наличии","descShort":"Венок · Размер M · Авторская работа","cardBenef":"Искусственные цветы · Ручная работа · Размер M","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер M"],"photo":"venok-premium-m.webp"},
  {"id":"2003","sku":"venok-premium-l","brandCode":"venki","brand":"Авторская мастерская","series":"Премиум венок","model":"Венок «Элегия» L","group":"venki","size":"L","btu":"-","area":0,"price":5000,"stock":"in_stock","stockLabel":"В наличии","descShort":"Венок · Размер L · Авторская работа","cardBenef":"Искусственные цветы · Ручная работа · Размер L","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер L"],"photo":"venok-premium-l.webp"},
  {"id":"2004","sku":"korzinka-premium-s","brandCode":"korzinki","brand":"Авторская мастерская","series":"Премиум корзинка","model":"Корзинка «Тихий сад» S","group":"korzinki","size":"S","btu":"-","area":0,"price":1800,"stock":"in_stock","stockLabel":"В наличии","descShort":"Корзинка · Размер S · Авторская работа","cardBenef":"Искусственные цветы · Ручная работа · Размер S","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер S"],"photo":"korzinka-premium-s.webp"},
  {"id":"2005","sku":"korzinka-premium-m","brandCode":"korzinki","brand":"Авторская мастерская","series":"Премиум корзинка","model":"Корзинка «Тихий сад» M","group":"korzinki","size":"M","btu":"-","area":0,"price":2800,"stock":"in_stock","stockLabel":"В наличии","descShort":"Корзинка · Размер M · Авторская работа","cardBenef":"Искусственные цветы · Ручная работа · Размер M","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер M"],"photo":"korzinka-premium-m.webp"},
  {"id":"2006","sku":"korzinka-premium-l","brandCode":"korzinki","brand":"Авторская мастерская","series":"Премиум корзинка","model":"Корзинка «Тихий сад» L","group":"korzinki","size":"L","btu":"-","area":0,"price":4200,"stock":"in_stock","stockLabel":"В наличии","descShort":"Корзинка · Размер L · Авторская работа","cardBenef":"Искусственные цветы · Ручная работа · Размер L","benefits":["Искусственные цветы","Авторская ручная работа","Стойкие материалы","Размер L"],"photo":"korzinka-premium-l.webp"}
];

var PRODUCT_OVERRIDES = {};
