const PRODUCTS = [
  {
    "id": "1001",
    "sku": "ultima-elysium-inv-07",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-I07PN",
    "group": "inv",
    "btu": "07",
    "area": 20,
    "price": 19950,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 07 BTU · до 20 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium.webp"
  },
  {
    "id": "1002",
    "sku": "ultima-elysium-inv-09",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-I09PN",
    "group": "inv",
    "btu": "09",
    "area": 25,
    "price": 21550,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 09 BTU · до 25 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium.webp"
  },
  {
    "id": "1003",
    "sku": "ultima-elysium-inv-12",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-I12PN",
    "group": "inv",
    "btu": "12",
    "area": 35,
    "price": 25550,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 12 BTU · до 35 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium.webp"
  },
  {
    "id": "1004",
    "sku": "ultima-elysium-inv-18",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-I18PN",
    "group": "inv",
    "btu": "18",
    "area": 50,
    "price": 45950,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 18 BTU · до 50 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium.webp"
  },
  {
    "id": "1005",
    "sku": "ultima-elysium-inv-24",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-I24PN",
    "group": "inv",
    "btu": "24",
    "area": 70,
    "price": 55250,
    "stock": "days_1_2",
    "stockLabel": "1–2 дня",
    "descShort": "Инвертор 24 BTU · до 70 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium.webp"
  },
  {
    "id": "1006",
    "sku": "ultima-elysium-inv-30",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-I30PN",
    "group": "inv",
    "btu": "30",
    "area": 90,
    "price": 71750,
    "stock": "days_3_5",
    "stockLabel": "3–5 дней",
    "descShort": "Инвертор 30 BTU · до 90 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium.webp"
  },
  {
    "id": "1007",
    "sku": "ultima-elysium-inv-36",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-I36PN",
    "group": "inv",
    "btu": "36",
    "area": 100,
    "price": 89950,
    "stock": "days_3_5",
    "stockLabel": "3–5 дней",
    "descShort": "Инвертор 36 BTU · до 100 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium.webp"
  },
  {
    "id": "1008",
    "sku": "ultima-elysium-nero-inv-07",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM NERO",
    "model": "ELN-I07PN",
    "group": "inv",
    "btu": "07",
    "area": 20,
    "price": 21950,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 07 BTU · до 20 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium-nero.webp"
  },
  {
    "id": "1009",
    "sku": "ultima-elysium-nero-inv-09",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM NERO",
    "model": "ELN-I09PN",
    "group": "inv",
    "btu": "09",
    "area": 25,
    "price": 23550,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 09 BTU · до 25 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium-nero.webp"
  },
  {
    "id": "1010",
    "sku": "ultima-elysium-nero-inv-12",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM NERO",
    "model": "ELN-I12PN",
    "group": "inv",
    "btu": "12",
    "area": 35,
    "price": 27550,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 12 BTU · до 35 м²",
    "cardBenef": "GREE · Wi‑Fi Ready · ECO · -15°C",
    "benefits": [
      "Компрессор GREE",
      "Wi‑Fi Ready",
      "Режим ECO",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "SOFT WIND",
      "3D AUTO Air",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elysium-nero.webp"
  },
  {
    "id": "1011",
    "sku": "ultima-eclipse-inv-07",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-I07PN",
    "group": "inv",
    "btu": "07",
    "area": 20,
    "price": 17990,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 07 BTU · до 20 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · SLEEP · -15°C",
    "benefits": [
      "Компрессор GMCC",
      "Wi‑Fi Ready",
      "Режим SLEEP",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-inv.webp"
  },
  {
    "id": "1012",
    "sku": "ultima-eclipse-inv-09",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-I09PN",
    "group": "inv",
    "btu": "09",
    "area": 25,
    "price": 19590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 09 BTU · до 25 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · SLEEP · -15°C",
    "benefits": [
      "Компрессор GMCC",
      "Wi‑Fi Ready",
      "Режим SLEEP",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-inv.webp"
  },
  {
    "id": "1013",
    "sku": "ultima-eclipse-inv-12",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-I12PN",
    "group": "inv",
    "btu": "12",
    "area": 35,
    "price": 23590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 12 BTU · до 35 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · SLEEP · -15°C",
    "benefits": [
      "Компрессор GMCC",
      "Wi‑Fi Ready",
      "Режим SLEEP",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-inv.webp"
  },
  {
    "id": "1014",
    "sku": "ultima-eclipse-inv-18",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-I18PN",
    "group": "inv",
    "btu": "18",
    "area": 50,
    "price": 40990,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 18 BTU · до 50 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · SLEEP · -15°C",
    "benefits": [
      "Компрессор GMCC",
      "Wi‑Fi Ready",
      "Режим SLEEP",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-inv.webp"
  },
  {
    "id": "1015",
    "sku": "ultima-eclipse-inv-24",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-I24PN",
    "group": "inv",
    "btu": "24",
    "area": 70,
    "price": 48990,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 24 BTU · до 70 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · SLEEP · -15°C",
    "benefits": [
      "Компрессор GMCC",
      "Wi‑Fi Ready",
      "Режим SLEEP",
      "Работа до -15°C",
      "Низкий уровень шума",
      "LED-дисплей",
      "5 скоростей",
      "2 года"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-inv.webp"
  },
  {
    "id": "1016",
    "sku": "ultima-elysium-onoff-07",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-07PN",
    "group": "onoff",
    "btu": "07",
    "area": 20,
    "price": 13590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 07 BTU · до 20 м²",
    "cardBenef": "GREE · ECO · SOFT WIND · А класс · -7°C",
    "benefits": [
      "Компрессор GREE",
      "ECO режим",
      "Режим SLEEP",
      "SOFT WIND — перфорированные жалюзи",
      "Низкий уровень шума",
      "LED-дисплей",
      "4 скорости",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elisyum-onoff.webp"
  },
  {
    "id": "1017",
    "sku": "ultima-elysium-onoff-09",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-09PN",
    "group": "onoff",
    "btu": "09",
    "area": 25,
    "price": 14790,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 09 BTU · до 25 м²",
    "cardBenef": "GREE · ECO · SOFT WIND · А класс · -7°C",
    "benefits": [
      "Компрессор GREE",
      "ECO режим",
      "Режим SLEEP",
      "SOFT WIND — перфорированные жалюзи",
      "Низкий уровень шума",
      "LED-дисплей",
      "4 скорости",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elisyum-onoff.webp"
  },
  {
    "id": "1018",
    "sku": "ultima-elysium-onoff-12",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-12PN",
    "group": "onoff",
    "btu": "12",
    "area": 35,
    "price": 20590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 12 BTU · до 35 м²",
    "cardBenef": "GREE · ECO · SOFT WIND · А класс · -7°C",
    "benefits": [
      "Компрессор GREE",
      "ECO режим",
      "Режим SLEEP",
      "SOFT WIND — перфорированные жалюзи",
      "Низкий уровень шума",
      "LED-дисплей",
      "4 скорости",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elisyum-onoff.webp"
  },
  {
    "id": "1019",
    "sku": "ultima-elysium-onoff-18",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-18PN",
    "group": "onoff",
    "btu": "18",
    "area": 50,
    "price": 34590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 18 BTU · до 50 м²",
    "cardBenef": "GREE · ECO · SOFT WIND · А класс · -7°C",
    "benefits": [
      "Компрессор GREE",
      "ECO режим",
      "Режим SLEEP",
      "SOFT WIND — перфорированные жалюзи",
      "Низкий уровень шума",
      "LED-дисплей",
      "4 скорости",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elisyum-onoff.webp"
  },
  {
    "id": "1020",
    "sku": "ultima-elysium-onoff-24",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM",
    "model": "ELB-24PN",
    "group": "onoff",
    "btu": "24",
    "area": 70,
    "price": 44990,
    "stock": "order_7",
    "stockLabel": "Под заказ 7 дней",
    "descShort": "On/Off 24 BTU · до 70 м²",
    "cardBenef": "GREE · ECO · SOFT WIND · А класс · -7°C",
    "benefits": [
      "Компрессор GREE",
      "ECO режим",
      "Режим SLEEP",
      "SOFT WIND — перфорированные жалюзи",
      "Низкий уровень шума",
      "LED-дисплей",
      "4 скорости",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elisyum-onoff.webp"
  },
  {
    "id": "1021",
    "sku": "ultima-elysium-nero-onoff-07",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM NERO",
    "model": "ELN-07PN",
    "group": "onoff",
    "btu": "07",
    "area": 20,
    "price": 15590,
    "stock": "days_3_5",
    "stockLabel": "3–5 дней",
    "descShort": "On/Off 07 BTU · до 20 м²",
    "cardBenef": "GREE · ECO · SOFT WIND · А класс · -7°C",
    "benefits": [
      "Компрессор GREE",
      "ECO режим",
      "Режим SLEEP",
      "SOFT WIND — перфорированные жалюзи",
      "Низкий уровень шума",
      "LED-дисплей",
      "4 скорости",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elisyum-nero-onoff.webp"
  },
  {
    "id": "1022",
    "sku": "ultima-elysium-nero-onoff-09",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM NERO",
    "model": "ELN-09PN",
    "group": "onoff",
    "btu": "09",
    "area": 25,
    "price": 16790,
    "stock": "days_3_5",
    "stockLabel": "3–5 дней",
    "descShort": "On/Off 09 BTU · до 25 м²",
    "cardBenef": "GREE · ECO · SOFT WIND · А класс · -7°C",
    "benefits": [
      "Компрессор GREE",
      "ECO режим",
      "Режим SLEEP",
      "SOFT WIND — перфорированные жалюзи",
      "Низкий уровень шума",
      "LED-дисплей",
      "4 скорости",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elisyum-nero-onoff.webp"
  },
  {
    "id": "1023",
    "sku": "ultima-elysium-nero-onoff-12",
    "brandCode": "uel",
    "brand": "ULTIMA COMFORT",
    "series": "ELYSIUM NERO",
    "model": "ELN-12PN",
    "group": "onoff",
    "btu": "12",
    "area": 35,
    "price": 22590,
    "stock": "days_3_5",
    "stockLabel": "3–5 дней",
    "descShort": "On/Off 12 BTU · до 35 м²",
    "cardBenef": "GREE · ECO · SOFT WIND · А класс · -7°C",
    "benefits": [
      "Компрессор GREE",
      "ECO режим",
      "Режим SLEEP",
      "SOFT WIND — перфорированные жалюзи",
      "Низкий уровень шума",
      "LED-дисплей",
      "4 скорости",
      "2 года"
    ],
    "compressor": "GREE",
    "freon": "R32",
    "photo": "ultima-elisyum-nero-onoff.webp"
  },
  {
    "id": "1024",
    "sku": "ultima-eclipse-onoff-07",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-07PN",
    "group": "onoff",
    "btu": "07",
    "area": 20,
    "price": 13390,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 07 BTU · до 20 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · TCL · -7°C R32 · ECO · 2 года",
    "benefits": [
      "Завод TCL",
      "Wi‑Fi Ready",
      "Фреон R32",
      "Smart Defrost",
      "5 скоростей",
      "Низкий шум",
      "A/A класс",
      "Функция теплого пуска",
      "Функция самодиагностики",
      "Eco – режим энергосбережения"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-onoff.webp"
  },
  {
    "id": "1025",
    "sku": "ultima-eclipse-onoff-09",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-09PN",
    "group": "onoff",
    "btu": "09",
    "area": 25,
    "price": 14590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 09 BTU · до 25 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · TCL · -7°C R32 · ECO · 2 года",
    "benefits": [
      "Завод TCL",
      "Wi‑Fi Ready",
      "Фреон R32",
      "Smart Defrost",
      "5 скоростей",
      "Низкий шум",
      "A/A класс",
      "Функция теплого пуска",
      "Функция самодиагностики",
      "Eco – режим энергосбережения"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-onoff.webp"
  },
  {
    "id": "1026",
    "sku": "ultima-eclipse-onoff-12",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-12PN",
    "group": "onoff",
    "btu": "12",
    "area": 35,
    "price": 19990,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 12 BTU · до 35 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · TCL · -7°C R32 · ECO · 2 года",
    "benefits": [
      "Завод TCL",
      "Wi‑Fi Ready",
      "Фреон R32",
      "Smart Defrost",
      "5 скоростей",
      "Низкий шум",
      "A/A класс",
      "Функция теплого пуска",
      "Функция самодиагностики",
      "Eco – режим энергосбережения"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-onoff.webp"
  },
  {
    "id": "1027",
    "sku": "ultima-eclipse-onoff-18",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-18PN",
    "group": "onoff",
    "btu": "18",
    "area": 50,
    "price": 33590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 18 BTU · до 50 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · TCL · -7°C R32 · ECO · 2 года",
    "benefits": [
      "Завод TCL",
      "Wi‑Fi Ready",
      "Фреон R32",
      "Smart Defrost",
      "5 скоростей",
      "Низкий шум",
      "A/A класс",
      "Функция теплого пуска",
      "Функция самодиагностики",
      "Eco – режим энергосбережения"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-onoff.webp"
  },
  {
    "id": "1028",
    "sku": "ultima-eclipse-onoff-24",
    "brandCode": "uec",
    "brand": "ULTIMA COMFORT",
    "series": "ECLIPSE",
    "model": "ECP-24PN",
    "group": "onoff",
    "btu": "24",
    "area": 70,
    "price": 43590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 24 BTU · до 70 м²",
    "cardBenef": "GMCC · Wi‑Fi Ready · TCL · -7°C R32 · ECO · 2 года",
    "benefits": [
      "Завод TCL",
      "Wi‑Fi Ready",
      "Фреон R32",
      "Smart Defrost",
      "5 скоростей",
      "Низкий шум",
      "A/A класс",
      "Функция теплого пуска",
      "Функция самодиагностики",
      "Eco – режим энергосбережения"
    ],
    "compressor": "GMCC",
    "freon": "R32",
    "photo": "ultima-eclipse-onoff.webp"
  },
  {
    "id": "1029",
    "sku": "eurohoff-callisto-07",
    "brandCode": "ec",
    "brand": "Eurohoff",
    "series": "CALLISTO",
    "model": "EM-07I",
    "group": "inv",
    "btu": "07",
    "area": 20,
    "price": 24990,
    "stock": "days_3_5",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 07 BTU · до 23 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности",
      "Работа до минус -15°C"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-callisto.webp"
  },
  {
    "id": "1030",
    "sku": "eurohoff-callisto-09",
    "brandCode": "ec",
    "brand": "Eurohoff",
    "series": "CALLISTO",
    "model": "EM-09I",
    "group": "inv",
    "btu": "09",
    "area": 25,
    "price": 26390,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 09 BTU · до 25 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности",
      "Работа до минус -15°C"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-callisto.webp"
  },
  {
    "id": "1031",
    "sku": "eurohoff-callisto-12",
    "brandCode": "ec",
    "brand": "Eurohoff",
    "series": "CALLISTO",
    "model": "EM-12I",
    "group": "inv",
    "btu": "12",
    "area": 35,
    "price": 28990,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 12 BTU · до 35 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности",
      "Работа до минус -15°C"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-callisto.webp"
  },
  {
    "id": "1032",
    "sku": "eurohoff-callisto-18",
    "brandCode": "ec",
    "brand": "Eurohoff",
    "series": "CALLISTO",
    "model": "EM-18I",
    "group": "inv",
    "btu": "18",
    "area": 50,
    "price": 49290,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 18 BTU · до 55 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности",
      "Работа до минус -15°C"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-callisto.webp"
  },
  {
    "id": "1033",
    "sku": "eurohoff-callisto-24",
    "brandCode": "ec",
    "brand": "Eurohoff",
    "series": "CALLISTO",
    "model": "EM-24I",
    "group": "inv",
    "btu": "24",
    "area": 70,
    "price": 59590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "Инвертор 24 BTU · до 80 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности",
      "Работа до минус -15°C"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-callisto.webp"
  },
  {
    "id": "1034",
    "sku": "eurohoff-astrid-07",
    "brandCode": "ea",
    "brand": "Eurohoff",
    "series": "ASTRID",
    "model": "AVE-07M",
    "group": "onoff",
    "btu": "07",
    "area": 20,
    "price": 16590,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 07 BTU · до 20 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-astrid.webp"
  },
  {
    "id": "1035",
    "sku": "eurohoff-astrid-09",
    "brandCode": "ea",
    "brand": "Eurohoff",
    "series": "ASTRID",
    "model": "AVE-09M",
    "group": "onoff",
    "btu": "09",
    "area": 25,
    "price": 18390,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 09 BTU · до 25 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-astrid.webp"
  },
  {
    "id": "1036",
    "sku": "eurohoff-astrid-12",
    "brandCode": "ea",
    "brand": "Eurohoff",
    "series": "ASTRID",
    "model": "AVE-12M",
    "group": "onoff",
    "btu": "12",
    "area": 35,
    "price": 23990,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 12 BTU · до 35 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-astrid.webp"
  },
  {
    "id": "1037",
    "sku": "eurohoff-astrid-18",
    "brandCode": "ea",
    "brand": "Eurohoff",
    "series": "ASTRID",
    "model": "AVE-18M",
    "group": "onoff",
    "btu": "18",
    "area": 50,
    "price": 38990,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 18 BTU · до 50 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-astrid.webp"
  },
  {
    "id": "1038",
    "sku": "eurohoff-astrid-24",
    "brandCode": "ea",
    "brand": "Eurohoff",
    "series": "ASTRID",
    "model": "AVE-24M",
    "group": "onoff",
    "btu": "24",
    "area": 70,
    "price": 46990,
    "stock": "in_stock",
    "stockLabel": "В наличии",
    "descShort": "On/Off 24 BTU · до 70 м²",
    "cardBenef": "GMCC Toshiba · Gold Fin · Самоочистка · HEALTH · Режим Turbo · 3 года",
    "benefits": [
      "Компрессор GMCC Toshiba",
      "Покрытие Gold Fin",
      "Автоочистка",
      "Тихая работа",
      "Ночной режим",
      "Режим комфортного сна",
      "HEALTH - режим здоровье",
      "Режим Turbo производительности"
    ],
    "compressor": "GMCC Toshiba",
    "freon": "R32",
    "photo": "eurohoff-astrid.webp"
  }
];
